services:
  web:
    image: nginx:latest
    ports:
      - "8040:80"
      - "8010:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/api
      - ./frontend/dist/browser:/var/www/html
      - ./backend/certs/webte_fei_stuba_sk.pem:/etc/nginx/certs/webte_fei_stuba_sk.pem
      - ./backend/certs/webte.fei.stuba.sk.key:/etc/nginx/certs/webte.fei.stuba.sk.key
  php:
    image: "backendphp"
    build: backend
    volumes:
      - ./backend:/var/www/api
  db:
    image: mysql:8.3.0
    restart: always
    volumes:
      - webte_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "nSqqSqw3U4YZ"
      MYSQL_DATABASE: "webte2skuskove"
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8011:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
    depends_on:
      - db

volumes:
  webte_mysql:
